spring:
  # Define H2 Console settings
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    platform: h2
    url: jdbc:h2:mem:testdb
    username: sa
    # Enable H2 Console

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
