# Please set an environment variable for the environment
spring:
  profiles:
    active: ${ENVIRONMENT}

# Error configuration
server:
  error:
    include-binding-errors: always
    include-exception: true
    include-message: always
    include-stacktrace: never

